name: Check Links in README

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6 AM UTC
  workflow_dispatch:     # allow manual runs

jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run lychee link checker on README
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: README.md --config .lychee.toml --verbose --no-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
